# Generated by Django 4.1.4 on 2022-12-12 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('article', models.CharField(max_length=300, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('a', 'В наличии'), ('b', 'Под заказ'), ('c', 'Ожидается поступление'), ('d', 'Нет в наличии'), ('e', 'Не производится')], default='a', max_length=1)),
                ('image', models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'webp'))])),
            ],
        ),
    ]
